# Generated by Django 4.2.23 on 2025-09-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='password',
            field=models.BinaryField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
