# Generated by Django 4.2.23 on 2025-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0002_alter_customusers_email_alter_customusers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AddConstraint(
            model_name='customusers',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email_constraint'),
        ),
    ]
