# Generated by Django 4.2.23 on 2025-09-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0003_alter_customusers_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTypes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'access_types',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='small_web.accesstypes')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='small_web.customusers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get', models.BooleanField(default=False)),
                ('post', models.BooleanField(default=False)),
                ('table_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_type', to='small_web.accesstypes')),
            ],
        ),
    ]
