# Generated by Django 4.2.23 on 2025-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0004_accesstypes_useraccess_custompermissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custompermissions',
            table='custom_permission',
        ),
        migrations.AlterModelTable(
            name='useraccess',
            table='user_access',
        ),
    ]
