# Generated by Django 4.2.23 on 2025-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0005_alter_custompermissions_table_alter_useraccess_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermissions',
            name='all_samples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
