# Generated by Django 4.2.23 on 2025-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0006_custompermissions_all_samples_customusers_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
