# Generated by Django 4.2.23 on 2025-09-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0007_customusers_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customusers',
            name='unique_email_constraint',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже существует'}, max_length=254, verbose_name='Почта'),
        ),
        migrations.AddConstraint(
            model_name='customusers',
            constraint=models.UniqueConstraint(fields=('email', 'is_active'), name='unique_email_constraint'),
        ),
    ]
